<?php

namespace backend\assets;

use yii\web\AssetBundle;

/**
 * Main backend application asset bundle.
 */
class AppAsset extends AssetBundle
{
    public $sourcePath = '@backend/assets';

    public $css = [
        'css/site.css',
    ];

    public $js = [
        'ckfinder/ckfinder.js',
        'js/main.js'
    ];

    public $depends = [
        'yii\web\YiiAsset',
        'yii\bootstrap4\BootstrapAsset',
    ];

    public function init()
    {
//        $this->registerJs['data'] = [
//            'ckFinderLicenseName' => \Yii::$app->params['ckFinderLicenseName'],
//            'ckFinderLicenseKey' => \Yii::$app->params['ckFinderLicenseKey']
//        ];

        parent::init(); // TODO: Change the autogenerated stub
    }
}
